// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Warn from "./Warn.bs.js";
import * as VerifiedEmail from "./VerifiedEmail.bs.js";
import * as UnverifiedEmail from "./UnverifiedEmail.bs.js";

function handleEmail(userInfo) {
  if (userInfo.isLogin) {
    if (userInfo.isEmailVerified) {
      return VerifiedEmail.handleVerifiedEmail(userInfo);
    } else {
      return UnverifiedEmail.handleUnverifiedEmail(userInfo);
    }
  } else {
    return Warn.handleNotLogin(undefined);
  }
}

export {
  handleEmail ,
}
/* No side effect */
