// Generated by ReScript, PLEASE EDIT WITH CARE

import * as VerifiedEmail from "./VerifiedEmail.bs.js";
import * as UnverifiedEmail from "./UnverifiedEmail.bs.js";

function handleEmail(emailInfo) {
  if (emailInfo.TAG === /* VerifiedEmailInfo */0) {
    return VerifiedEmail.handleVerifiedEmail(emailInfo._0);
  } else {
    return UnverifiedEmail.handleUnverifiedEmail(emailInfo._0);
  }
}

export {
  handleEmail ,
}
/* No side effect */
