// Generated by ReScript, PLEASE EDIT WITH CARE


function handleUnverifiedEmail(emailInfo) {
  console.log("Email: " + emailInfo.email + "");
}

export {
  handleUnverifiedEmail ,
}
/* No side effect */
