// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Email from "./Email.bs.js";

function handleGuestName(userInfo) {
  console.log("guest name: " + userInfo.name + "");
}

function handleUserInfo(userInfo) {
  console.log("user name: " + userInfo.name + ", user id: " + userInfo.id + "");
}

function handleResponse(res) {
  if (res.TAG === /* Ok */0) {
    var data = res._0.data;
    if (data.TAG !== /* LoginUserInfo */0) {
      return handleGuestName(data._0);
    }
    var userInfo = data._0;
    handleUserInfo(userInfo);
    return Email.handleEmail(userInfo.emailInfo);
  }
  console.log(res._0.error);
}

export {
  handleGuestName ,
  handleUserInfo ,
  handleResponse ,
}
/* No side effect */
