// Generated by ReScript, PLEASE EDIT WITH CARE


function handleVerifiedEmail(emailInfo) {
  console.log("Email: " + emailInfo.email + ", verified at " + emailInfo.verifiedAt + "");
}

export {
  handleVerifiedEmail ,
}
/* No side effect */
