// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PrimitiveTypes from "./PrimitiveTypes.bs.js";

var add = PrimitiveTypes.Int.add;

console.log(add(10, 7));

var invalid = "invalid";

export {
  add ,
  invalid ,
}
/*  Not a pure module */
