// Generated by ReScript, PLEASE EDIT WITH CARE


var name = "Neo";

var word = "hello";

var greetings = "" + name + " say " + word + " to you";

var condition = {
  contents: true
};

condition.contents = false;

function addInt(a, b) {
  return a + b | 0;
}

function addFloat(a, b) {
  return a + b;
}

function concat(a, b) {
  return a + b;
}

console.log("Hello ReScript");

function add(a, b) {
  return a + b | 0;
}

function minus(a, b) {
  return a - b | 0;
}

var Int = {
  add: add,
  minus: minus
};

function add$1(a, b) {
  return a + b;
}

function minus$1(a, b) {
  return a - b;
}

var Float = {
  add: add$1,
  minus: minus$1
};

var s = "Hello ReScript";

var c = /* 'a' */97;

var i = 5;

var f = 5.1;

var f2 = 5;

var b = true;

export {
  s ,
  c ,
  name ,
  word ,
  greetings ,
  i ,
  f ,
  f2 ,
  b ,
  condition ,
  addInt ,
  addFloat ,
  concat ,
  Int ,
  Float ,
}
/*  Not a pure module */
