// Generated by ReScript, PLEASE EDIT WITH CARE


var name = "Neo";

var word = "hello";

var greetings = "" + name + " say " + word + " to you";

var condition = {
  contents: true
};

condition.contents = false;

function addInt(a, b) {
  return a + b | 0;
}

function addFloat(a, b) {
  return a + b;
}

function concat(a, b) {
  return a + b;
}

console.log("Hello ReScript");

var s = "Hello ReScript";

var c = /* 'a' */97;

var i = 5;

var f = 5.1;

var f2 = 5;

var b = true;

export {
  s ,
  c ,
  name ,
  word ,
  greetings ,
  i ,
  f ,
  f2 ,
  b ,
  condition ,
  addInt ,
  addFloat ,
  concat ,
}
/*  Not a pure module */
