// Generated by ReScript, PLEASE EDIT WITH CARE


var messi = {
  name: "Messi",
  age: 35
};

var cthulhu = {
  age: 9999,
  hasTentacles: true
};

function getAge(entity) {
  return entity.age;
}

console.log(messi.age);

console.log(cthulhu.age);

export {
  messi ,
  cthulhu ,
  getAge ,
}
/*  Not a pure module */
