// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Warn from "./Warn.bs.js";
import * as Email from "./Email.bs.js";

function handleGuestName(userInfo) {
  if (!userInfo.isLogin) {
    console.log("guest name: " + userInfo.name + "");
    return ;
  }
  
}

function handleUserInfo(userInfo) {
  if (userInfo.isLogin) {
    console.log("user name: " + userInfo.name + ", user id: " + userInfo.id + "");
    return ;
  } else {
    return handleGuestName(userInfo);
  }
}

function handleResponse(res) {
  var error = res.error;
  if (error !== undefined) {
    return Warn.handleError(error);
  }
  var userInfo = res.data;
  if (userInfo !== undefined) {
    handleUserInfo(userInfo);
    return Email.handleEmail(userInfo);
  }
  
}

export {
  handleGuestName ,
  handleUserInfo ,
  handleResponse ,
}
/* No side effect */
