// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Warn from "./Warn.bs.js";

function handleVerifiedEmail(userInfo) {
  if (userInfo.isLogin) {
    if (userInfo.isEmailVerified) {
      console.log("Email: " + userInfo.email + ", verified at " + userInfo.emailVerifiedAt + "");
      return ;
    } else {
      return ;
    }
  } else {
    return Warn.handleNotLogin(undefined);
  }
}

export {
  handleVerifiedEmail ,
}
/* No side effect */
