// Generated by ReScript, PLEASE EDIT WITH CARE


function handleError(error) {
  console.error(error);
}

function handleNotLogin(param) {
  console.warn("User is not login");
}

export {
  handleError ,
  handleNotLogin ,
}
/* No side effect */
